### PR TITLE
Add pyinstaller compatibility

### PR DESCRIPTION
**Pull request by Legorooj**
@avylove

### CODE REVIEW

**Comment by avylove** [comment]
I'm really struggling with this one. There are two main issues I see.

The first is that the hidden imports are static. I think it would be reasonable if the code didn't get executed, but it looks like the code that specifies the hidden imports gets executed.

The other is it's a lot of boilerplate and pushes files for all users even though it's not useful to most users. I'm not sure why all of this can't be done by placing something like
`__pyinstaller_hiddenimports = ['jinxed.terminfo.ansicon', 'jinxed.terminfo.vtwin10']`
in a file that can be read when anylizing the AST.

That said, this is an issue that comes up a lot, but at this point I'm not sure if it's better to add all this boilerplate or add something to the docs and a link in the error message.

**Comment by Legorooj** [comment]
@avylove I could add these hooks into PyInstaller's hooks-contrib package if you wanted, which will be automatically installed with PyInstaller as of next release.

**Comment by avylove** [comment]
@Legorooj That would be really awesome!

**Comment by Legorooj** [comment]
@avylove I'll add it in. I'm going to leave this PR open for now so I remember.

**Comment by Legorooj** [comment]
I've added this to our contributed package. The changes should go live on PyPI by the end of this month - PyInstaller 4.0.

**Comment by avylove** [comment]
Awesome! Thanks so much @Legorooj!

**Pull request closed without merging**
